[colors.primary]
background = "#120707"
foreground = "#c3c1c1"

[colors.cursor]
text = "#120707"
cursor = "#c3c1c1"

[colors.vi_mode_cursor]
text = "#120707"
cursor = "#c3c1c1"

[colors.search.matches]
foreground = "#120707"
background = "#c3c1c1"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6a5656"
background = "#c3c1c1"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#120707"
red = "#A35A5B"
green = "#D0745D"
yellow = "#E4883F"
blue = "#EB9A69"
magenta = "#FBC876"
cyan = "#F7B185"
white = "#c3c1c1"

[colors.bright]
black = "#6a5656"
red = "#A35A5B"
green = "#D0745D"
yellow = "#E4883F"
blue = "#EB9A69"
magenta = "#FBC876"
cyan = "#F7B185"
white = "#c3c1c1"

[colors.dim]
black = "#c3c1c1"
red = "#A35A5B"
green = "#FBC876"
yellow = "#E4883F"
blue = "#EB9A69"
magenta = "#D0745D"
cyan = "#F7B185"
white = "#6a5656"

