[colors]
background = '#1207078e'
black = '#120707'
blue = '#A35A5B'
cursor = '#c3c1c1'
cyan = '#D0745D'
foreground = '#c3c1c1'
green = '#E4883F'
magenta = '#EB9A69'
red = '#FBC876'
tabs = '#c3c1c1'
tabs-active = '#F7B185'
white = '#c3c1c1'
yellow = '#c3c1c1'
dim-black = '#1207078e'
dim-blue = '#A35A5B8e'
dim-cyan = '#D0745D8e'
dim-foreground = '#c3c1c18e'
dim-green = '#E4883F8e'
dim-magenta = '#EB9A698e'
dim-red = '#FBC8768e'
dim-white = '#F7B1858e'
dim-yellow = '#c3c1c18e'
light-black = '#A35A5B'
light-blue = '#D0745D'
light-cyan = '#E4883F'
light-foreground = '#EB9A69'
light-green = '#FBC876'
light-magenta = '#F7B185'
light-red = '#c3c1c1'
light-white = '#A35A5B'
light-yellow = '#D0745D'
